### ISSUE TITLE
Fine-tuning guided diffusion conditionally/unconditionally on other data

### ISSUE THREAD

**Issue by akrlowicz** [openai/guided-diffusion#110]
I want to fine tune one of the diffusion models trained on ImageNet, to some other data like CelebA or CIFAR-10. I wonder two things:
- does my pretrained model needs to be unconditional? or can it be conditioned on ImageNet classes but can be tuned on unconditional CelebA or with classes from CIFAR-10?
- maybe trivial but does image sizes must agree between ImageNet data and my target data from pretraining? aka if I have CIFAR-10 32x32 I need model trained on the same resolution of ImageNet?

**Comment by yuanlinwang** [comment]
@akrlowicz hello!have you found the answer? Is the fine tune getting good results?
