### ISSUE TITLE
Figures Appendix C of the paper

### ISSUE THREAD

**Issue by SANCHES-Pedro** [openai/guided-diffusion#3]
Hello,

Congrats on the great work and thanks for sharing the code!

I wonder how you generated Figure 8 of Appendix C in your paper?

How are the images so similar, even when the scale is so reduced? Is there any conditioning beyond classifier guidance?

Many thanks!

**Comment by woctezuma** [comment]
This is the picture.

![Fig8 AppC](https://i.imgur.com/8m3MiWy.jpg)

**Comment by crowsonkb** [comment]
It looks like the diffusion models themselves can be class-conditional, notice how this model's forward() has a class label input that must be specified if the model is the conditional variant: https://github.com/openai/guided-diffusion/blob/main/guided_diffusion/unet.py#L638

**Comment by unixpickle** [comment]
The key word in the caption is "fixed seed". We fix the noise used to sample, which tends to result in very similar images even when changing classifier scale. To achieve this, simply call `torch.manual_seed(n)` with some fixed seed `n` before sampling.

**Comment by SANCHES-Pedro** [comment]
I see, thanks.

I got a bit confused because the images at scale 0.0 are also class-conditioned. But the conditioning uses the other mechanism. The image illustrates how classifier guidance improves image quality, but the generated images are conditioned anyway... 

Thanks!
