### ISSUE TITLE
How to set hyper-parameters for training a diffusion model

### ISSUE THREAD

**Issue by ewrfcas** [openai/guided-diffusion#46]
Should I set 'lr_anneal_steps' and 'weight_decay' or just keep them in default during training a diffusion model?

**Comment by unixpickle** [comment]
In our experiments, we did not use lr_anneal_steps or weight_decay.

**Comment by Spidartist** [comment]
@unixpickle so did you let it run and stop it whenever you want?

**Comment by wwj723452017** [comment]
@Spidartist hi,did you figure out this problem?I've ran for two days and still no sign to stop,maybe I should set'lr_anneal_steps'?
