### ISSUE TITLE
infinite while loop in TrainLoop.run_loop

### ISSUE THREAD

**Issue by tahaceritli** [openai/guided-diffusion#59]
Hi,

Thanks for sharing this repo!

I am trying to train the models from scratch. It seems that TrainLoop(...).run_loop() function has a while loop that is running on infinitely, as self.lr_anneal_steps is set 0. I'm referring to the code snippet given below:
`
while (
            not self.lr_anneal_steps
            or self.step + self.resume_step < self.lr_anneal_steps
        ):
`

I suppose that it is safe to define a num_iterations parameter and use it in this loop? If so, I suppose this parameter is the one reported in Table 11-13 of the arXiv paper.

I would appreciate if you could clarify this.

Best,
Taha

**Comment by hxy-123-coder** [comment]
Hello！I have same question with you.Do you solve it? Could you share your solution?Thanks a lot.

**Comment by tahaceritli** [comment]
I have just defined a separate variable for the number of iterations and checked if self.step is lower than that, like: 
```
num_iterations = 600000
while self.step < num_iterations:
...
```
I haven't tried to reproduce the tables in the paper though.

**Comment by hxy-123-coder** [comment]
Ok,Thank you!
