### ISSUE TITLE
Any plan to release "optimized version" according to Appendix A?

### ISSUE THREAD

**Issue by AranKomat** [openai/guided-diffusion#6]
I believe the current version is of "naive" implementation, as the number I got from benchmarking is close to it.

I tried FusedAdam from Apex, but it didn't improve the throughput much, so either that's not what you used, or fused GroupNorm-Swish has a bigger benefit. 

Do you have any plan to release thie optimized version or any code snippet one can use to improve the code?

**Comment by unixpickle** [comment]
We currently do not have plans to release the optimized version.

Note that a significant amount of the speedup comes from using larger per-GPU batch sizes, which this codebase should be capable of given enough GPU memory. One subtle corollary is that fused ops and more-efficient Adam will use less memory, allowing a larger batch size to fit on the same GPU.
