### ISSUE TITLE
out of memory in FID evaluation

### ISSUE THREAD

**Issue by forever208** [openai/guided-diffusion#82]
failed to allocate 64.00M (67108864 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory

Does anyone have a problem using GPU when doing evaluation?

**Comment by ridhimagarg** [comment]
I think you have to use better GPU, but for me I didn't face use of memory while evaluating.

What is the configuration of your GPU?

**Comment by forever208** [comment]
I roughly know that it was the problem with the CPU memory, thanks @ridhimagarg
