### ISSUE TITLE
Non-Square Images

### ISSUE THREAD

**Issue by Squeemos** [openai/guided-diffusion#83]
I'm using this unet architecture to create images, but I'm curious about using non-square images. Current the only problems seems to be in the output_blocks, specifically with ``` th.cat([h, hs.pop(), dim=1]) ```
With non-square images the dimensions aren't correct, which is understandable.

Is there a good way to go about getting this setup to use non-square images? What's interesting is inside the u-net init it takes in an image size but doesn't use it anywhere else

**Comment by tevkhieu** [comment]
Did you find a way to create non-squared images?
