### ISSUE TITLE
Training doesn't really work

### ISSUE THREAD

**Issue by baniasbaabe** [openai/guided-diffusion#9]
When running 

`python scripts/image_train.py --data_dir path/to/images $MODEL_FLAGS $DIFFUSION_FLAGS $TRAIN_FLAGS
`
The code will run for 2 seconds and finish it without creating some `/tmp` folder. There isn't any error neither.

**Comment by woctezuma** [comment]
This is about the parent repository: https://github.com/openai/improved-diffusion/issues

**Comment by baniasbaabe** [comment]
Okay thanks, I will open an issue in the parent repo
